sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run test
  - npm run test:check-coverage
  - npm run test:report-coverage
after_success:
  # No need to build as it is done in the prepublish script
  - npm run semantic-release
branches:
  only:
    - master
